### ISSUE TITLE
Pretrained model files

### ISSUE THREAD

**Issue by siddhu001** [uwnlp/twittercommunities#1]
HI Aaron,

I want to reproduce the results of your community member retrival paper in NAACL 2018. Can you please provide me with pretrained models namely "phraser.bin" used in make_dataframe.py  and "../models/myexpdir" used in embedding.py to assist me in my work.

**Comment by ajaech** [comment]
Hi,

I added the phraser.bin file to the github repo. You can download the model file from this link [https://ssli.ee.washington.edu/data/twittercommunities/model.tar.gz](https://ssli.ee.washington.edu/data/twittercommunities/model.tar.gz)
