### ISSUE TITLE
want some file's sample

### ISSUE THREAD

**Issue by gaoli1537** [uwnlp/twittercommunities#2]
My respected teacher:
          I am very interested in reading your paper, but I ran the code and found some files missing, such as'/g/ssli/data/surf/word2vec_full.txt.gz' and 'csv input files',Could you send me some examples of these documents? Some small samples are fine, because I am not very convenient to use tweetAPI here.my email is wycmglq@outlook.com, looking forward to your reply.

**Comment by ajaech** [comment]
The input csv files are comma separated with the following columns
dir,file,lang,text,timestamp,user

An example row would be like this:
/some/path/to/file,en,text of the tweet,1493011987.0,123456678

I will email you the word embedding file.
